# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[battery]
full_symbol = ''
charging_symbol = ''
discharging_symbol = ''

[cmd_duration]
disabled = true

[directory]
truncation_length = 8
truncation_symbol = '…/'
truncate_to_repo = false

[git_branch]
truncation_length = 64
truncation_symbol = '…'
style = "bold green"

[git_status]
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[aws]
disabled = true

[gcloud]
disabled = true
