syntax on

" fix broken backspace
set backspace=indent,eol,start

" indentation
set expandtab
set shiftwidth=2
set softtabstop=2

" ruler
set ruler
set rulerformat=%l,%v

" tabs for makefiles
autocmd FileType make setlocal tabstop=4 shiftwidth=4 softtabstop=0 noexpandtab

" tabs for shellscripts
autocmd FileType make setlocal tabstop=4 shiftwidth=4 softtabstop=0 noexpandtab

" textwidth for gitcommit
au FileType gitcommit setlocal tw=72