#!/usr/bin/env bash

# navigation
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias pd+='pushd'
alias pd-='popd'

# ls
alias ls='ls --color'
alias l='ls'
alias ll='ls -l'
alias la='ls -la'
alias lt='ls -ltra'
alias l.='ls -d .*'

# safety
alias rm='rm -I --preserve-root'
alias mv='mv -i'
alias cp='cp -i'
alias ln='ln -i'
alias chown='chown --preserve-root'
alias chgrp='chgrp --preserve-root'
alias chmod='chmod --preserve-root'

# misc
alias top='htop'
alias path='echo -e ${PATH//:/\\n}'
alias nowdate='date +"%d-%m-%Y"'
alias nowtime='date +"%T"'
alias now='date +"%d-%m-%Y %T"'

alias sui='sudo -i'
alias sul='sudo su -l'
alias zv='nc -zv'
alias viro='vi -R'
alias cls='clear'
alias df='df -h'
alias du='du -ch'
alias apug='tree -apug'
alias igrep='grep -i'
alias hgrep='history | grep'
alias h='history'
alias j='jobs -l'
alias lsmnt='mount | column -t'
alias ping='ping -c 5'
alias less='less -r'
alias ntl='netstat -ntl'
alias ntlp='netstat -ntlp'
alias egrep='grep --color -E'
alias fgrep='grep --color -F'
alias fal='alias | grep -i'
# print all user defined functions
alias lsfn="declare -F | awk '{print \$NF}' | sort | egrep -v '^_'"

# colorization
alias grep='grep --color=auto'
alias bzgrep='bzgrep --color=auto'
alias zgrep='zgrep --color=auto'
alias diff='diff --color'

# docker
if command -v docker >/dev/null 2>&1; then
    # basic
    alias dco='docker container'
    alias dcx='docker context'
    alias de='docker exec'
    alias dim='docker image'
    alias din='docker inspect'
    alias dl='docker logs'
    alias dn='docker network'
    alias ds='docker system'
    alias dv='docker volume'
    alias dr='docker run'
    # useful
    alias dspa='docker system prune -a'
    alias dps='docker ps --format "table {{.ID}}\t{{.Names}}\t{{.Image}}\t{{.Status}}"'
    alias dpsl='docker ps --format "table {{.ID}}\t{{.Names}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}"'
fi

# docker-compose
if command -v docker-compose >/dev/null 2>&1; then
    alias doco='docker compose'
fi

# kubectl
if command -v kubectl >/dev/null 2>&1; then
    alias k='kubectl'
    alias ka='kubectl apply'
    alias kcr='kubectl create'
    alias kcf='kubectl config'
    alias kdx='kubectl delete'
    alias kde='kubectl describe'
    alias kg='kubectl get'
    alias kl='kubectl logs -f'
    alias kga='kubectl get all'
    alias kdxa='kubectl delete all --all'
    alias kgp='kubectl get pods'
    alias kgpw='watch -n 1 kubectl get pods'
    alias kdxp='kubectl delete pods'
    alias kdxpa='kubectl delete pods --all'
    alias kgs='kubectl get services'
    alias kdxs='kubectl delete services'
    alias kdxsa='kubectl delete services --all'
    alias kgd='kubectl get deployments'
    alias kdxd='kubectl delete deployments'
    alias kdxda='kubectl delete deployments --all'
    alias kcns='kubectl create namespace'
    alias kdxns='kubectl delete namespace'
    # get default namespace
    alias kgdns="kubectl config view --minify --output 'jsonpath={..namespace}'"
    # set default namespace
    alias ksdns='kubectl config set-context --current --namespace'
    # delete default namespace (sets to "default")
    alias kdxdns='kubectl config set-context --current --namespace default'
    # get port-forwards
    alias kgpf="ps -ef | grep 'kubectl' | grep 'port-forward' | awk '{print \$(NF-1), \$NF}'"
    # delete port-forwards
    alias kdxpf='pgrep -fi "kubectl.*port-forward" | xargs kill -9'
fi

# gcloud
if command -v gcloud >/dev/null 2>&1; then
    # basic
    alias gc="gcloud"
    # useful
    alias gccfga='gcloud config configurations activate'
    alias gckcred='gcloud container clusters get-credentials'
fi
