#!/usr/bin/env bash

# variables
JAVA_HOME="$HOME/opt/jdk/jdk-17"
export JAVA_HOME

# path
PATH="$JAVA_HOME/bin:$PATH"
PATH="$HOME/opt/build/apache-maven/bin:$PATH"
PATH="$HOME/opt/build/gradle/bin:$PATH"
PATH="$HOME/opt/build/bazel/bin:$PATH"
export PATH
