#!/usr/bin/env bash

# variables
JAVA_HOME="$HOME/opt/sdk/jdk-17"
JQ_COLORS="0;90:0;39:0;39:0;39:0;32:1;39:1;39:1;34"
export JAVA_HOME JQ_COLORS

# path
PATH="$JAVA_HOME/bin:$PATH"
PATH="$HOME/opt/cli/build/maven/bin:$PATH"
PATH="$HOME/opt/cli/build/gradle/bin:$PATH"
export PATH
