#!/bin/bash

# enable vi-mode
set -o vi

# enable ctrl-l in vi-mode
bind -m vi-insert "\C-l":clear-screen

# ignore file on path completion with cd
complete -d cd

if ! shopt -q globstar; then
	shopt -s globstar
fi

if ! shopt -q autocd; then
	shopt -s autocd
fi

if [ ! -r ~/.dircolors ]; then
	dircolors -p > ~/.dircolors 
fi
eval "$(dircolors -b ~/.dircolors)"

