#!/bin/bash

tabname() {
	if [ -z "$BACKUP" ]; then
		BACKUP=$PS1
	fi
	TITLE="\[\e]2;$*\a\]"
	PS1=${BACKUP}${TITLE}
}

find_bin_dirs() {
        find "$1" -maxdepth 2 -follow -not -path '*/\.*' -type d -name bin -printf "%p:"
}
