#!/bin/bash

# navigation
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias pd+='pushd'
alias pd-='popd'

# ls
alias l='ls'
alias ll='ls -l'
alias la='ls -la'
alias lt='ls -ltra'
alias l.='ls -d .*'

# safety
alias rm='rm -I --preserve-root'
alias mv='mv -i'
alias cp='cp -i'
alias ln='ln -i'
alias chown='chown --preserve-root'
alias chgrp='chgrp --preserve-root'
alias chmod='chmod --preserve-root'

# apt
alias update='sudo apt-get update'
alias upgrade='sudo apt-get upgrade'
alias install='sudo apt-get install'
alias remove='sudo apt-get remove'
alias autoremove='sudo apt-get autoremove'
alias purge='sudo apt-get remove --purge'
alias dist-upgrade='sudo apt-get dist-upgrade'
alias search='apt-cache search'
alias show='apt-cache show'
alias policy='apt-cache policy'

# misc
alias xclip="xclip -sel clip"
alias top='htop'
alias glances='glances --theme-white'
alias bat='batcat'
alias cat='rich'
alias path='echo -e ${PATH//:/\\n}'
alias nowdate='date +"%d-%m-%Y"'
alias nowtime='date +"%T"'
alias now='date +"%d-%m-%Y %T"'
alias sui='sudo -i'
alias sul='sudo su -l'
alias ntlp='sudo netstat -ntlp'
alias zv='nc -zv'
alias viro='vi -R'
alias cls='clear'
alias df='df -h'
alias du='du -ch'
alias apug='tree -apug'
alias igrep='grep -i'
alias hgrep='history | grep'
alias h='history'
alias j='jobs -l'
alias lsmnt='mount | column -t'
alias vi=vim
alias ping='ping -c 5'
alias fastping='ping -c 10 -i .2'
alias less='less -r'
alias gph='git-prompt-help'

# colorization
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias zgrep='zgrep --color=auto'
alias diff='diff --color'

# docker
if command -v docker > /dev/null 2>&1; then
	alias dco='docker container'
	alias dim='docker image'
	alias dvo='docker volume'
	alias dne='docker network'
	alias dlo='docker logs'
	alias din='docker inspect'
	alias dex='docker exec -it'
	alias dps='docker ps --format "table {{.ID}}\t{{.Names}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}"'
fi

# docker-compose
if command -v docker-compose > /dev/null 2>&1; then
	alias doco='docker-compose'
	alias docodown='docker-compose down'
	alias docoup='docker-compose up'
	alias docoupd='docker-compose up -d'
	alias docore='docker-compose down && docker-compose up -d'
	alias docolog='docker-compose logs'
fi

# ansible
if command -v ansible-playbook > /dev/null 2>&1; then
	alias ap='ansible-playbook'
	alias apc='ansible-playbook --check'
fi
