#!/bin/bash

PATH="/bin:/usr/bin:/usr/local/bin"
if [ "$(id -u)" -eq 0 ]; then
	PATH="$PATH:/sbin:/usr/sbin:/usr/local/sbin"
fi

PATH="$PATH:$HOME/bin"
PATH="$PATH:$HOME/bin/backup"
PATH="$PATH:$HOME/.local/bin"

export PATH
