#!/usr/bin/env bash
# shellcheck disable=SC2046

# homebrew environment
eval $(/opt/homebrew/bin/brew shellenv)

# homebrew completion
if type brew &>/dev/null; then
    HOMEBREW_PREFIX="$(brew --prefix)"
    if [[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]; then
        # shellcheck source=/dev/null
        source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
    else
        for COMPLETION in "${HOMEBREW_PREFIX}/etc/bash_completion.d/"*; do
            # shellcheck source=/dev/null
            [[ -r "${COMPLETION}" ]] && source "${COMPLETION}"
        done
    fi
fi

# homebrew gnu utils
for d in "$HOMEBREW_PREFIX"/opt/*/libexec/gnubin; do export PATH=$d:$PATH; done
for d in "$HOMEBREW_PREFIX"/opt/*/libexec/gnuman; do export MANPATH=$d:$MANPATH; done
