#!/usr/bin/env bash

BASH_SILENCE_DEPRECATION_WARNING=1
export BASH_SILENCE_DEPRECATION_WARNING

# ls wrapper that hides system directories
alias ls='$HOME/bin/ls.sh -F --color=auto --group-directories-first'

# homebrew completion
if type brew &>/dev/null; then
    HOMEBREW_PREFIX="$(brew --prefix)"
    if [[ -r "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh" ]]; then
        # shellcheck source=/dev/null
        source "${HOMEBREW_PREFIX}/etc/profile.d/bash_completion.sh"
    else
        for COMPLETION in "${HOMEBREW_PREFIX}/etc/bash_completion.d/"*; do
            # shellcheck source=/dev/null
            [[ -r "${COMPLETION}" ]] && source "${COMPLETION}"
        done
    fi
fi

# macos specific aliases
alias ntl='netstat -na -p TCP | grep -i "listen"'
alias ntlp='netstat -na -p TCP | grep -i "listen" | grep'
