#!/usr/bin/env bash

# starship
eval "$(starship init bash)"

# colima
export TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE=/var/run/docker.sock
export DOCKER_HOST="unix://$HOME/.colima/default/docker.sock"

# bat as manpager
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# fzf
# shellcheck disable=SC1090
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# thefuck
eval "$(thefuck --alias)"

# difftool
difftool() {
    # shellcheck disable=SC2068
    /Applications/IntelliJ\ IDEA.app/Contents/MacOS/idea diff $@ &>/dev/null
}

# kubectl port-forward
alias kpf="ps -ef | grep kubectl | grep port-forward | awk '{print \$(NF-1), \$NF}'"
